name: 'CI'

on:
  push:
    branches:
      - 'main'
  pull_request:
  schedule:
    - cron: "0 0 * * SUN"

jobs:
  tests:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        lisp:
          - sbcl-bin
          - ccl-bin
          
    env:
      LISP: ${{ matrix.lisp }}

    steps:
      - name: Install libsecp256k1
        run: sudo apt install -y libsecp256k1-dev 
      - uses: actions/checkout@v1
      - uses: 40ants/setup-lisp@v1
      - uses: 40ants/run-tests@v2
        with:
          asdf-system: secp256k1
  tests-macos:
    runs-on: macos-latest
    
    strategy:
      matrix:
        lisp:
          - sbcl-bin
          - ccl-bin
          
    env:
      LISP: ${{ matrix.lisp }}

    steps:
      - name: Install libsecp256k1
        run: |
          brew tap cuber/homebrew-libsecp256k1
          brew install libsecp256k1
      - uses: actions/checkout@v1
      - uses: 40ants/setup-lisp@v1
      - uses: 40ants/run-tests@v2
        with:
          asdf-system: secp256k1
